packages:
  - apps/**/*
  - packages/*

catalog:
  '@egoist/tailwindcss-icons': 1.9.0
  '@iconify-json/mingcute': 1.2.5
  '@t3-oss/env-core': 0.13.8
  '@tailwindcss/postcss': 4.1.13
  '@tailwindcss/typography': 0.5.18
  dotenv-expand: 12.0.3
  tailwind-scrollbar: 4.0.2
  tailwind-variants: 3.1.1
  tailwindcss: 4.1.13
  tailwindcss-animate: 1.0.7
  tailwindcss-safe-area: 1.1.0
  tailwindcss-uikit-colors: 1.0.0
  typescript: 5.9.2
  zod: 4.1.11

onlyBuiltDependencies:
  - esbuild
  - puppeteer
